In [1]:
# 第十二章，pandas高级应用

In [2]:
# 我们已经学习了unique和value_counts 可以从数组中提取不同的值，并分别计算频率

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
values = pd.Series(['apple','orange','apple','apple'] * 2 )

In [6]:
values


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [7]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [8]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [9]:
# 在数据仓库中，最好的方法是用所谓的包含不同值的维表，将主要的参数存储为引用维表整数键

In [18]:
values = pd.Series([0,1,0,0] * 2)

In [19]:
dim = pd.Series(['apple','orange'])

In [20]:
# 可以使用 take 方法存储原始的字符串 Series

In [21]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [22]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2 

In [23]:
N = len(fruits)

In [37]:
df = pd.DataFrame({'fruit':fruits,
                  'basket_id':np.arange(N),
                  'count':np.random.randint(3,15,size = N),
                  'weight':np.random.uniform(0,4,size = N)},
                  columns = ['basket_id','fruit','count','weight'])

In [38]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [39]:
df

basket_id   fruit  count    weight
0          0   apple      3  2.059926
1          1  orange     10  1.939406
2          2   apple      7  2.324726
3          3   apple      7  1.005567
4          4   apple      5  3.934854
5          5  orange      4  0.495555
6          6   apple      9  1.942366
7          7   apple      8  1.174711

In [40]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [41]:
df['fruit'].type()

AttributeError: 'Series' object has no attribute 'type'

In [43]:
furit_cat = df['fruit'].astype('category')

In [44]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [45]:
furit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [47]:
df['fruit'].dtype()

TypeError: 'numpy.dtype' object is not callable

In [48]:
furit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [49]:
c = furit_cat.values

In [50]:
c

[apple, orange, apple, apple, apple, orange, apple, apple]
Categories (2, object): [apple, orange]

In [51]:
type(c)

pandas.core.arrays.categorical.Categorical

In [52]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [53]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [54]:
# 可以将DF的列通过分配转换结果，转换为分类

In [55]:
df['fruit'] = df['fruit'].astype('category')

In [56]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [57]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [58]:
df.count

<bound method DataFrame.count of    basket_id   fruit  count    weight
0          0   apple      3  2.059926
1          1  orange     10  1.939406
2          2   apple      7  2.324726
3          3   apple      7  1.005567
4          4   apple      5  3.934854
5          5  orange      4  0.495555
6          6   apple      9  1.942366
7          7   apple      8  1.174711>

In [59]:
df.basket_id

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
Name: basket_id, dtype: int32

In [60]:
# 还可以从其他 Python 序列直接创建 pandas.Cagegorical

In [61]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [62]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [63]:
my_categories.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [64]:
my_categories.value_counts

<bound method Categorical.value_counts of [foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]>

In [65]:
my_categories.categories

Index(['bar', 'baz', 'foo'], dtype='object')

In [66]:
# 如果已经从其他源获得了额分类编码，还可以使用form_codes 构造器

In [67]:
categories = ['foo','bar','baz']

In [74]:
codes = [0,1,2,0,0,0,1]

In [75]:
my_cat_2 = pd.Categorical.from_codes(codes,categories)

In [76]:
my_cat_2

[foo, bar, baz, foo, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [77]:
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)

In [78]:
ordered_cat

[foo, bar, baz, foo, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [79]:
# 用分类进行计算

In [80]:
np.random.seed(12345)

In [81]:
draws = np.random.randn(1000)

In [82]:
draws

array([-2.04707659e-01,  4.78943338e-01, -5.19438715e-01, -5.55730304e-01,
        1.96578057e+00,  1.39340583e+00,  9.29078767e-02,  2.81746153e-01,
        7.69022568e-01,  1.24643474e+00,  1.00718936e+00, -1.29622111e+00,
        2.74991633e-01,  2.28912879e-01,  1.35291684e+00,  8.86429341e-01,
       -2.00163731e+00, -3.71842537e-01,  1.66902531e+00, -4.38569736e-01,
       -5.39741446e-01,  4.76985010e-01,  3.24894392e+00, -1.02122752e+00,
       -5.77087303e-01,  1.24121276e-01,  3.02613562e-01,  5.23772068e-01,
        9.40277775e-04,  1.34380979e+00, -7.13543985e-01, -8.31153539e-01,
       -2.37023165e+00, -1.86076079e+00, -8.60757398e-01,  5.60145293e-01,
       -1.26593449e+00,  1.19827125e-01, -1.06351245e+00,  3.32882716e-01,
       -2.35941881e+00, -1.99542955e-01, -1.54199553e+00, -9.70735912e-01,
       -1.30703025e+00,  2.86349747e-01,  3.77984111e-01, -7.53886535e-01,
        3.31285650e-01,  1.34974221e+00,  6.98766888e-02,  2.46674110e-01,
       -1.18616011e-02,  

In [83]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [84]:
# 计算着个数据的分为面元，提取一些统计信息

In [85]:
bins = pd.qcut(draws,4)

In [86]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [87]:
# 使用labels参数qcut 实现

In [88]:
binss = pd.qcut(draws,4,labels = ['Q1','Q2','Q3','Q4'])

In [89]:
binss

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [90]:
binss.codes

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3, 3, 0, 2, 2, 3, 3, 0, 1, 3, 1, 1, 2,
       3, 0, 1, 2, 2, 2, 2, 3, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 0,
       0, 2, 2, 0, 2, 3, 2, 2, 1, 3, 3, 0, 0, 2, 3, 1, 3, 2, 2, 3, 3, 0,
       1, 0, 1, 0, 0, 3, 3, 3, 3, 1, 1, 0, 0, 2, 2, 0, 3, 2, 3, 3, 0, 3,
       1, 3, 2, 3, 1, 3, 2, 3, 2, 0, 2, 2, 0, 1, 1, 0, 1, 1, 3, 3, 1, 3,
       1, 2, 3, 0, 0, 1, 2, 1, 3, 0, 0, 0, 2, 3, 1, 1, 2, 1, 1, 1, 0, 0,
       3, 3, 2, 2, 3, 1, 1, 2, 0, 3, 2, 1, 2, 1, 1, 1, 3, 3, 0, 3, 1, 0,
       2, 0, 1, 3, 3, 1, 1, 1, 0, 3, 0, 3, 1, 3, 3, 3, 3, 1, 3, 0, 0, 1,
       0, 0, 2, 1, 1, 1, 0, 3, 3, 3, 0, 1, 1, 1, 0, 0, 3, 2, 3, 3, 0, 0,
       3, 2, 3, 1, 2, 1, 0, 0, 0, 1, 0, 1, 3, 2, 1, 3, 1, 3, 0, 2, 3, 1,
       1, 2, 0, 0, 2, 3, 3, 2, 1, 2, 0, 0, 0, 3, 1, 0, 0, 2, 2, 2, 0, 1,
       3, 1, 3, 0, 2, 1, 3, 1, 3, 0, 1, 0, 2, 0, 1, 1, 0, 2, 0, 3, 1, 3,
       0, 0, 1, 2, 1, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 3, 0,
       0, 3, 0, 2, 1, 2, 0, 2, 2, 1, 3, 3, 1, 3, 3,

In [91]:
binss 

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [94]:
binss = pd.Series(binss,name='hahha')

In [95]:
binss

0      Q2
1      Q3
2      Q2
3      Q2
4      Q4
5      Q4
6      Q3
7      Q3
8      Q4
9      Q4
10     Q4
11     Q1
12     Q3
13     Q3
14     Q4
15     Q4
16     Q1
17     Q2
18     Q4
19     Q2
20     Q2
21     Q3
22     Q4
23     Q1
24     Q2
25     Q3
26     Q3
27     Q3
28     Q3
29     Q4
       ..
970    Q2
971    Q1
972    Q2
973    Q4
974    Q3
975    Q1
976    Q1
977    Q2
978    Q2
979    Q3
980    Q3
981    Q1
982    Q3
983    Q4
984    Q2
985    Q4
986    Q1
987    Q4
988    Q1
989    Q3
990    Q1
991    Q4
992    Q1
993    Q4
994    Q2
995    Q3
996    Q2
997    Q1
998    Q3
999    Q4
Name: hahha, Length: 1000, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [96]:
results = (pd.Series(draws).groupby(binss).agg(['count','min','max']).reset_index())

In [97]:
results

hahha  count       min       max
0    Q1    250 -2.949343 -0.685484
1    Q2    250 -0.683066 -0.010115
2    Q3    250 -0.010032  0.628894
3    Q4    250  0.634238  3.927528

In [98]:
# 用分类提高性能

In [99]:
# 如果在一个特定数据集上做大量分析，将其转化为分类可以极大提高效率

In [100]:
N = 1000000

In [101]:
draws = pd.Series(np.random.randn(N))

In [102]:
labesl = pd.Series(['foo','bar','baz','qux'] *(N //4))

In [103]:
# 将标签转换为分类

In [104]:
categories = labesl.astype('category')

In [105]:
categories

0         foo
1         bar
2         baz
3         qux
4         foo
5         bar
6         baz
7         qux
8         foo
9         bar
10        baz
11        qux
12        foo
13        bar
14        baz
15        qux
16        foo
17        bar
18        baz
19        qux
20        foo
21        bar
22        baz
23        qux
24        foo
25        bar
26        baz
27        qux
28        foo
29        bar
         ... 
999970    baz
999971    qux
999972    foo
999973    bar
999974    baz
999975    qux
999976    foo
999977    bar
999978    baz
999979    qux
999980    foo
999981    bar
999982    baz
999983    qux
999984    foo
999985    bar
999986    baz
999987    qux
999988    foo
999989    bar
999990    baz
999991    qux
999992    foo
999993    bar
999994    baz
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: category
Categories (4, object): [bar, baz, foo, qux]

In [107]:
labesl

0         foo
1         bar
2         baz
3         qux
4         foo
5         bar
6         baz
7         qux
8         foo
9         bar
10        baz
11        qux
12        foo
13        bar
14        baz
15        qux
16        foo
17        bar
18        baz
19        qux
20        foo
21        bar
22        baz
23        qux
24        foo
25        bar
26        baz
27        qux
28        foo
29        bar
         ... 
999970    baz
999971    qux
999972    foo
999973    bar
999974    baz
999975    qux
999976    foo
999977    bar
999978    baz
999979    qux
999980    foo
999981    bar
999982    baz
999983    qux
999984    foo
999985    bar
999986    baz
999987    qux
999988    foo
999989    bar
999990    baz
999991    qux
999992    foo
999993    bar
999994    baz
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: object

In [108]:
labels.memory_usage()

NameError: name 'labels' is not defined

In [109]:
labesl.memory_usage()

8000080

In [110]:
categories.memory_usage()

1000272

In [111]:
# 标签使用的内存比分类多得多

In [114]:
%time_ = labesl.astype('category')

ERROR:root:Line magic function `%time_` not found.


In [113]:
%matplotlib inline

In [115]:
out.backward()

NameError: name 'out' is not defined

In [116]:
s = pd.Series(['a','b','c','d'] * 2)

In [117]:
cat_s = s.astype('category')

In [118]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [119]:
# 为建模创建虚拟变量

In [120]:
#当使用统计后机器学习工具时，通常会将分类数据转换为虚拟变量，也称为one-hot编码

In [121]:
# 之前学习了在分组操作中 apply 方法， 还有一个 transform 方法，和 apply相似

In [122]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,    'value': np.arange(12.)}) 

In [123]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [124]:
# 按键进行分组

In [125]:
g = df.groupby('key').value

In [126]:
g

In [127]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [128]:
# 假设我们想参数一个和 df['value] 形状相同的 Series， 但值替换为按键分组的平均值，我们可以传递函数 lambda x: x.mean(())

In [129]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [130]:
g

In [131]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [132]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [133]:
# 于apply相似，transfrom会返回Series，但结果必须与输入大小相同

In [135]:
g.transform(lambda x : x * 2)  # 将每个分组乘2

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [136]:
# 在举一个复杂的例子，我们可以计算每个分组的降序排名

In [138]:
g.transform(lambda x: x.rank(ascending = False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [139]:
g

In [140]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [141]:
# transform 和 apply 很相似也很重要