In [1]:
# 第五章，pandas入门

In [2]:
# pandas是基于Numy数组构建的，基于数组的函数和不使用for循环的数据处理

In [3]:
# pandas 的数据结构介绍

In [4]:
# Series和DataFrame

In [5]:
# Series 是一种类似于一维数组的对象，由一组数据（各种Numpy数据类型）以及一组与之相关的数据标签（即索引）组成

In [6]:
import pandas as pd

In [7]:
from pandas import Series,DataFrame

In [8]:
obj = pd.Series([4,7,-5,3])

In [9]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [10]:
# 索引 + 数据 

In [11]:
# 索引在左，数据在右

In [12]:
# 可以通过Seriec的values 和 index属性获得其数组的表示形式和索引对象

In [13]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [14]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
# 根据自己需求创建索引

In [16]:
obj2 = pd.Series([4,7,-5,3],index=['a','b','c','d'])

In [17]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [18]:
obj2['a']

4

In [19]:
obj['b']

KeyError: 'b'

In [20]:
obj2['b']

7

In [21]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [22]:
obj2>2

a     True
b     True
c    False
d     True
dtype: bool

In [23]:
obj2[obj2>2]

a    4
b    7
d    3
dtype: int64

In [24]:
# 还可以将 Series 看成是一个定长的有序字典，因为它是索引值到数据值的一个映射

In [25]:
# 如果数据被存放在一个个Python字典中，也可以通过这个字典创建Series

In [26]:
sdata = {'aa':444,'bb':666,'cc':777}

In [27]:
obj3 = pd.Series(sdata)

In [28]:
obj3

aa    444
bb    666
cc    777
dtype: int64

In [29]:
# 我们将使用缺失（missing）或NA表示数据缺失

In [30]:
# pandas 中国 isnull 和 notnull 函数可以用来检测缺失数据

In [31]:
stats = {'bb','aa''dd}

SyntaxError: EOL while scanning string literal (<ipython-input-31-77b978d5616a>, line 1)

In [32]:
stats = {'bb','dd','aa'}

In [33]:
obj4 = pd.Series(obj3,stats)

In [34]:
obj4

dd      NaN
bb    666.0
aa    444.0
dtype: float64

In [35]:
pd.isnull(obj4)

dd     True
bb    False
aa    False
dtype: bool

In [36]:
pd.notnull(obj4)

dd    False
bb     True
aa     True
dtype: bool

In [37]:
obj4.isnull()

dd     True
bb    False
aa    False
dtype: bool

In [38]:
obj3

aa    444
bb    666
cc    777
dtype: int64

In [39]:
obj4

dd      NaN
bb    666.0
aa    444.0
dtype: float64

In [40]:
obj3 + obj4

aa     888.0
bb    1332.0
cc       NaN
dd       NaN
dtype: float64

In [41]:
# Series 对象本身及其索引都有一个name属性，该属性非常重要

In [42]:
obj4.name

In [43]:
obj4.name = 'hyhyhy'

In [44]:
obj4.name

'hyhyhy'

In [45]:
obj4.index.name

In [46]:
obj3.index.name

In [47]:
obj4.index.name = 'state'

In [48]:
obj4

state
dd      NaN
bb    666.0
aa    444.0
Name: hyhyhy, dtype: float64

In [49]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [50]:
obj.index = ['a','b','c','d']

In [51]:
obj

a    4
b    7
c   -5
d    3
dtype: int64

In [52]:
# DataFrame

In [53]:
# DataFrame 是一个表格型数据结构

In [54]:
# 有行索引也有列索引，可以看做又 Series 组成的字典 （共用同一索引）

In [55]:
# 创建 DataFrame 的常见方法：直接传入一个由等长列表或NumPy数组成的字典

In [56]:
data = {'state':['haha','yyy','dada','gsg'],'year':[1997,2000,2555],'pop':[2,5,6]}

In [57]:
frame = pd.DataFrame(data)

ValueError: arrays must all be same length

In [58]:
# 测试：字典中的value的长度必须一致

In [59]:
data = {'state':['haha','yyy','dada','gsg'],'year':[1997,2000,255，5],'pop':[2,3，5,6]}

SyntaxError: invalid character in identifier (<ipython-input-59-58bff9117d11>, line 1)

In [60]:
data = {'state':['haha','yyy','dada','gsg'],'year':[1997,2000,255，5],'pop':[2,3，5,6]}

SyntaxError: invalid character in identifier (<ipython-input-60-58bff9117d11>, line 1)

In [61]:
data = {'state':['haha','yyy','dada','gsg'],'year':[1997,2000,255,5],'pop':[2,3,5,6]}

In [62]:
frame = pd.DataFrame(data)

In [63]:
frmae

NameError: name 'frmae' is not defined

In [64]:
frame

state  year  pop
0  haha  1997    2
1   yyy  2000    3
2  dada   255    5
3   gsg     5    6

In [65]:
# 对于特别大的 DateFrame head 方法会取前五行

In [66]:
frame.head()

state  year  pop
0  haha  1997    2
1   yyy  2000    3
2  dada   255    5
3   gsg     5    6

In [67]:
# 如果指定了列序列， DataFrame 的列就会按照指定顺序进行排列

In [68]:
pd.DataFrame(data,columns = ['year','pop','state'])

year  pop state
0  1997    2  haha
1  2000    3   yyy
2   255    5  dada
3     5    6   gsg

In [69]:
# 如果传入的列在数据中找不到，就会在结果中产生缺失值

In [70]:
frame2 = pd.DataFrame(data,columns = ['year','pop','state','aa'])

In [71]:
frame2

year  pop state   aa
0  1997    2  haha  NaN
1  2000    3   yyy  NaN
2   255    5  dada  NaN
3     5    6   gsg  NaN

In [72]:
frame2.index = ['one','two','three']

ValueError: Length mismatch: Expected axis has 4 elements, new values have 3 elements

In [73]:
frame2.index = ['one','two','three','four']

In [74]:
frame2

year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN

In [75]:
frame2.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [76]:
frame2.columns

Index(['year', 'pop', 'state', 'aa'], dtype='object')

In [77]:
frames.year

NameError: name 'frames' is not defined

In [78]:
frame2.year

one      1997
two      2000
three     255
four        5
Name: year, dtype: int64

In [79]:
frame2.pop

<bound method NDFrame.pop of        year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN>

In [80]:
frame2.pop

<bound method NDFrame.pop of        year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN>

In [81]:
frame2

year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN

In [82]:
frame.year

0    1997
1    2000
2     255
3       5
Name: year, dtype: int64

In [83]:
frame2.year

one      1997
two      2000
three     255
four        5
Name: year, dtype: int64

In [84]:
frame2.pop

<bound method NDFrame.pop of        year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN>

In [85]:
frame2.aa

one      NaN
two      NaN
three    NaN
four     NaN
Name: aa, dtype: object

In [86]:
frame2.state

one      haha
two       yyy
three    dada
four      gsg
Name: state, dtype: object

In [87]:
frame2

year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN

In [88]:
frame2['pop']

one      2
two      3
three    5
four     6
Name: pop, dtype: int64

In [89]:
frame2['aa']

one      NaN
two      NaN
three    NaN
four     NaN
Name: aa, dtype: object

In [90]:
# 通过类似于字典标记的方式或属性的方式，可以将 DataFrame 的列获取为一个 Series

In [91]:
frame2.loc['aa']

KeyError: 'the label [aa] is not in the [index]'

In [92]:
frame2.loc['three']

year      255
pop         5
state    dada
aa        NaN
Name: three, dtype: object

In [93]:
frame2

year  pop state   aa
one    1997    2  haha  NaN
two    2000    3   yyy  NaN
three   255    5  dada  NaN
four      5    6   gsg  NaN

In [94]:
val = pd.Series([-1.20,5,6,9],index =['tow','one','three','four'])

In [95]:
frame2['aa'] = val

In [96]:
frame2

year  pop state   aa
one    1997    2  haha  5.0
two    2000    3   yyy  NaN
three   255    5  dada  6.0
four      5    6   gsg  9.0

In [97]:
val = pd.Series([-1.20,5,6,9],index =['two','one','three','four'])

In [98]:
frame2['aa'] = val

In [99]:
frame2

year  pop state   aa
one    1997    2  haha  5.0
two    2000    3   yyy -1.2
three   255    5  dada  6.0
four      5    6   gsg  9.0

In [100]:
# 如果将列表或者数组赋值给某个列时，长度必须跟 DataFrame 的长度相匹配，如果赋值的是一个 Series， 就会精确匹配 DataFrame 的索引

In [101]:
# 关键字 del 用于删除列

In [102]:
frame2

year  pop state   aa
one    1997    2  haha  5.0
two    2000    3   yyy -1.2
three   255    5  dada  6.0
four      5    6   gsg  9.0

In [103]:
del frame2['aa']

In [104]:
frame2

year  pop state
one    1997    2  haha
two    2000    3   yyy
three   255    5  dada
four      5    6   gsg

In [105]:
# 不能用 frame2.aa 来创建一个新的列

In [106]:
# 通过索引放回的列之后相应数据的视图而已，不是副本。因此，对返回的Series 所做的任何就地修改全部都会反映到源 DataFrame 上。 通过 Series.copy的方法即可指定复制列

In [107]:
# 嵌套字典

In [108]:
aa = {'bb':{2001:2.4,2002:3}, 'cc':{3000:5,6000:9}}

In [109]:
frame3 = pd.DataFrame(aa)

In [110]:
frame3

bb   cc
2001  2.4  NaN
2002  3.0  NaN
3000  NaN  5.0
6000  NaN  9.0

In [111]:
# 嵌套字典时，外层的字典的键作为列，内层键则为行索引

In [112]:
# 对 DataFrame 进行转置

In [113]:
frame3.T

2001  2002  3000  6000
bb   2.4   3.0   NaN   NaN
cc   NaN   NaN   5.0   9.0

In [114]:
frame3

bb   cc
2001  2.4  NaN
2002  3.0  NaN
3000  NaN  5.0
6000  NaN  9.0

In [115]:
frame['bb'][:-1]

KeyError: 'bb'

In [116]:
frame3['bb'][:-1]

2001    2.4
2002    3.0
3000    NaN
Name: bb, dtype: float64

In [117]:
pdd = {'bb':frame3['bb'][:-1], 'cc':frame3['cc'][:-2]}

In [118]:
pdd

{'bb': 2001    2.4
 2002    3.0
 3000    NaN
 Name: bb, dtype: float64, 'cc': 2001   NaN
 2002   NaN
 Name: cc, dtype: float64}

In [119]:
pdd

{'bb': 2001    2.4
 2002    3.0
 3000    NaN
 Name: bb, dtype: float64, 'cc': 2001   NaN
 2002   NaN
 Name: cc, dtype: float64}

In [120]:
pdd_ = pd.DataFrame(pdd)

In [121]:
pdd_

bb  cc
2001  2.4 NaN
2002  3.0 NaN
3000  NaN NaN

In [122]:
frame3

bb   cc
2001  2.4  NaN
2002  3.0  NaN
3000  NaN  5.0
6000  NaN  9.0

In [123]:
frame3['cc'][:-2]

2001   NaN
2002   NaN
Name: cc, dtype: float64

In [124]:
frame3['cc'][-2]

KeyError: -2

In [125]:
frame3['cc'][-1]

KeyError: -1

In [126]:
frame3['cc'][:-1]

2001    NaN
2002    NaN
3000    5.0
Name: cc, dtype: float64

In [127]:
frame3['cc'][:]

2001    NaN
2002    NaN
3000    5.0
6000    9.0
Name: cc, dtype: float64

In [128]:
a = [2,1,4,6,7]

In [129]:
a

[2, 1, 4, 6, 7]

In [130]:
a[-1:-2]

[]

In [131]:
a[-2:-1]

[6]

In [132]:
a[-3:-2]

[4]

In [133]:
a{-1}

SyntaxError: invalid syntax (<ipython-input-133-b2c2242f50bb>, line 1)

In [134]:
a[-1:]

[7]

In [135]:
import numpy as np

In [136]:
a = np.arange(5)

In [137]:
a

array([0, 1, 2, 3, 4])

In [138]:
a = np.arange([5,2])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [139]:
a = np.arange((6,2))

TypeError: arange: scalar arguments expected instead of a tuple.

In [140]:
a = np.ones([5,2])

In [141]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [142]:
aa = pd.DataFrame(a)

In [143]:
aa

0    1
0  1.0  1.0
1  1.0  1.0
2  1.0  1.0
3  1.0  1.0
4  1.0  1.0

In [144]:
aa = np.ones([2,3,4])

In [145]:
aa

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [146]:
bb = pd.DataFrame(aa)

ValueError: Must pass 2-d input

In [147]:
aa = {'eqwe':np.ones([2,3]),'arqr':'hellow'}

In [148]:
bb =pd.DataFrame(aa)

ValueError: If using all scalar values, you must pass an index

In [149]:
aa

{'arqr': 'hellow', 'eqwe': array([[1., 1., 1.],
        [1., 1., 1.]])}

In [150]:
aa = {'eqwe':np.ones(2),'arqr':'hellow'}

In [151]:
aa

{'arqr': 'hellow', 'eqwe': array([1., 1.])}

In [152]:
bb =pd.DataFrame(aa)

In [153]:
bb

eqwe    arqr
0   1.0  hellow
1   1.0  hellow

In [154]:
# pandas 的索引对象负责管理轴标签和其他元数据（比如轴名称）

In [155]:
obj = pd.Series(range(3),index = ['a','b','c'])

In [156]:
obj

a    0
b    1
c    2
dtype: int64

In [157]:
index = obj.index

In [158]:
index

Index(['a', 'b', 'c'], dtype='object')

In [159]:
index[1:]

Index(['b', 'c'], dtype='object')

In [160]:
index[1] = 'cc'

TypeError: Index does not support mutable operations

In [161]:
# Index 对象不可变

In [162]:
labels = pd.Index(np.arange(3))

In [163]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [164]:
obj2 = pd.Series([0,1,2],dtype = 'int64')

In [165]:
obj2

0    0
1    1
2    2
dtype: int64

In [166]:
obj2.index is labels

False

In [167]:
obj2 = pd.Series([1.5,-2.1,0],dtype = 'int64')

In [168]:
obj2.index is labels

False

In [169]:
obj2.index

RangeIndex(start=0, stop=3, step=1)

In [170]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [171]:
# 重新索引

In [172]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])

In [173]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [174]:
# 使用Series的reindex将会根据新索引重排

In [175]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [176]:
boj2

NameError: name 'boj2' is not defined

In [177]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [178]:
# 重新索引时的插值操作

In [179]:
o = pd.Series(['blue','purple','yellow',index = [0,2,4]])

SyntaxError: invalid syntax (<ipython-input-179-bce6c664db96>, line 1)

In [180]:
o = pd.Series(['blue','purple','yellow'],index = [0,2,4])

In [181]:
o

0      blue
2    purple
4    yellow
dtype: object

In [182]:
o1 = o.reindex(range(6),method = 'ffill')

In [183]:
o1

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [184]:
# 向前置填充

In [185]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','b','c'],columns=['d','e','f'])

In [186]:
frame

d  e  f
a  0  1  2
b  3  4  5
c  6  7  8

In [187]:
frame2 = frame.reindex(['a','b','c','d'])

In [188]:
frame2

d    e    f
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN

In [189]:
# 列也可以用 columns 关键字工薪索引

In [190]:
frame2 = frame.reindex(columns=['a','b','c','d'])

In [191]:
frame2

a   b   c  d
a NaN NaN NaN  0
b NaN NaN NaN  3
c NaN NaN NaN  6

In [192]:
# 丢弃指定轴上的项

In [194]:
# drop 方法返回的是在一个指定轴上删除了指定值的新对象

In [195]:
obj = pd.Series(np.arange(5),index=['a','b','c','d','e'])

In [196]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [197]:
new_obj = obj.drop('c')

In [198]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [199]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [200]:
obj.drop(['b','c'])

a    0
d    3
e    4
dtype: int32

In [201]:
# 对于 DataFrame 可以删除任意轴上的索引值

In [202]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index= ['a','b','c','d'],columns=['one','two','three','four'])

In [203]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [204]:
data.drop(['a','b'])

one  two  three  four
c    8    9     10    11
d   12   13     14    15

In [205]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [206]:
data.drop(['one','tow',axis = 1])

SyntaxError: invalid syntax (<ipython-input-206-3b94d375fd55>, line 1)

In [207]:
data.drop(['one','tow'],axis = 1)

KeyError: "['tow'] not found in axis"

In [208]:
data.drop(['one','two'],axis = 1)

three  four
a      2     3
b      6     7
c     10    11
d     14    15

In [209]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [210]:
data.drop(['one','two'],axis = 1,inplace=True)

In [211]:
data

three  four
a      2     3
b      6     7
c     10    11
d     14    15

In [212]:
# 使用 inplace 选项可以永久修改对象，不会返回新的对象

In [213]:
# 小心使用 Inplace 会彻底删除原来的数据

In [214]:
# 索引、选取和过滤

In [215]:
# Series 的索引和 Numpy 数组类似

In [216]:
obj = pd.Series(np.arange(4),index=['a','b','c','d'])

In [217]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [218]:
obj[1]

1

In [219]:
obj[2]

2

In [220]:
obj[1:2]

b    1
dtype: int32

In [221]:
obj[1:3]

b    1
c    2
dtype: int32

In [222]:
obj['a']

0

In [223]:
obj['b']

1

In [224]:
#  利用标签的切片和普通的 Python 切片运算不同，其末端是包含额

In [225]:
obj['b':'c']

b    1
c    2
dtype: int32

In [226]:
# 赋值操作

In [227]:
obj['b':'c'] = 5

In [228]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [229]:
# 用一个值或序列对 DF 进行索引其实就是获取一个或者多个列

In [230]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['one','two','three','four'],columns=[1,2,3,4])

In [231]:
data

1   2   3   4
one     0   1   2   3
two     4   5   6   7
three   8   9  10  11
four   12  13  14  15

In [232]:
data[1]

one       0
two       4
three     8
four     12
Name: 1, dtype: int32

In [233]:
data[2]

one       1
two       5
three     9
four     13
Name: 2, dtype: int32

In [234]:
data[1:2]

1  2  3  4
two  4  5  6  7

In [235]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['one','two','three','four'],columns=['a','b','c','d'])

In [236]:
data

a   b   c   d
one     0   1   2   3
two     4   5   6   7
three   8   9  10  11
four   12  13  14  15

In [237]:
data['a']

one       0
two       4
three     8
four     12
Name: a, dtype: int32

In [238]:
data['b']

one       1
two       5
three     9
four     13
Name: b, dtype: int32

In [239]:
data['c']

one       2
two       6
three    10
four     14
Name: c, dtype: int32

In [240]:
data['a':'c']

KeyError: 'a'

In [241]:
data

a   b   c   d
one     0   1   2   3
two     4   5   6   7
three   8   9  10  11
four   12  13  14  15

In [242]:
data['a']

one       0
two       4
three     8
four     12
Name: a, dtype: int32

In [243]:
data['one']

KeyError: 'one'

In [244]:
data[:1]

a  b  c  d
one  0  1  2  3

In [245]:
data[:2]

a  b  c  d
one  0  1  2  3
two  4  5  6  7

In [1]:
# 用 loc 和 iloc 进行选取

In [2]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),    .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],    .....:                     columns=['one', 'two', 'three', 

SyntaxError: invalid syntax (<ipython-input-2-680ffb175df6>, line 1)

In [3]:
import pandas as pd 

In [4]:
import numpy as np

In [5]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])

In [6]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [7]:
data.loc['b',['two','four']]

two     5
four    7
Name: b, dtype: int32

In [8]:
# loc 轴标签索引， illoc 整数索引

In [9]:
data.ilococ[2,[1,2,3]]

AttributeError: 'DataFrame' object has no attribute 'ilococ'

In [10]:
data.iloc[2,[1,2,3]]

two       9
three    10
four     11
Name: c, dtype: int32

In [11]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [12]:
data.loc[:'c',[:'two']]

SyntaxError: invalid syntax (<ipython-input-12-f8ef101a61bd>, line 1)

In [13]:
data.loc[:'c',:'two']

one  two
a    0    1
b    4    5
c    8    9

In [14]:
# 整数索引

In [15]:
from pandas import  Series

In [16]:
ser = pd.Series(np.arange(3.))

In [17]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [18]:
ser[-1]

KeyError: -1

In [19]:
ser2 = pd.Series(np.arange(3),index=['a','b','c'])

In [20]:
ser2

a    0
b    1
c    2
dtype: int32

In [21]:
ser2[-1]

2

In [22]:
# 轴索引含有整数，一般都使用标签索引，使用loc(标签) iloc(整数)

In [23]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [24]:
ser2.loc[:1]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [25]:
ser2.loc[:'b']

a    0
b    1
dtype: int32

In [26]:
ser.iloc[:1]

0    0.0
dtype: float64

In [27]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [28]:
# 数据运算和数据对齐

In [29]:
# pandas 最重要的一个功能，可以对不同索引的对象进行算术运算

In [30]:
s1 = pd.Series([7,5,9,5],index=['a','b','c','d'])

In [31]:
s2 = pd.Series([7,5,9,5],index=['a','c','e','f'])

In [32]:
s1

a    7
b    5
c    9
d    5
dtype: int64

In [33]:
s2

a    7
c    5
e    9
f    5
dtype: int64

In [34]:
s1 +s2

a    14.0
b     NaN
c    14.0
d     NaN
e     NaN
f     NaN
dtype: float64

In [35]:
# 自动的数据对齐操作在不重叠的索引处引入了NA值缺失值会在算术过程中传播

In [36]:
# 对于 DataFrame 对齐操作会同时发生在行和列上

In [37]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3,=)),index = ['oh','te','co'],columns=list['bcd'])

SyntaxError: invalid syntax (<ipython-input-37-aab97fe8662d>, line 1)

In [38]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3,=)),index = ['oh','te','co'],columns=list('bcd'))

SyntaxError: invalid syntax (<ipython-input-38-0cd3767f5ec1>, line 1)

In [39]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['oh','te','co'],columns=list('bcd'))

In [40]:
df1

b  c  d
oh  0  1  2
te  3  4  5
co  6  7  8

In [41]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)),index = ['oh','te','ut','Or'],columns=list('bde'))

In [42]:
df2

b   d   e
oh  0   1   2
te  3   4   5
ut  6   7   8
Or  9  10  11

In [43]:
df1 + df2

b   c    d   e
Or  NaN NaN  NaN NaN
co  NaN NaN  NaN NaN
oh  0.0 NaN  3.0 NaN
te  6.0 NaN  9.0 NaN
ut  NaN NaN  NaN NaN

In [44]:
# 在算术方法中填充

In [45]:
#  使用关键字 fill_value = **  可以改变填充的值

In [46]:
# DataFrame 和 Seriec 之间的运算

In [47]:
arr = np.arange(12).reshape((3,4))

In [48]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
arr[0]

array([0, 1, 2, 3])

In [50]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [51]:
# 简单了解广播的机制   当我们从arr 减去 arr[0] 每一行都会执行这个操作

In [52]:
# DataFrame 和 Series 之间的运算也类似，应用的是广播的机制

In [53]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['U','o','t'])

ValueError: Shape of passed values is (3, 4), indices imply (3, 3)

In [54]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['U','o','t','r'])

In [55]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [56]:
series = frame.iloc(0)

In [57]:
series

In [58]:
list(series)

NotImplementedError: ix is not iterable

In [59]:
series

In [60]:
series = frame.iloc[0]

In [61]:
series

b    0
d    1
e    2
Name: U, dtype: int32

In [62]:
# 默认情况下，DF 和 SE 之间的算术运算会将 SE 的索引匹配到 DF的列，然后沿着行一直向下广播

In [63]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [64]:
frame - series

b  d  e
U  0  0  0
o  3  3  3
t  6  6  6
r  9  9  9

In [65]:
serr = frame.ilod[1]

AttributeError: 'DataFrame' object has no attribute 'ilod'

In [66]:
serr = frame.iloc[1]

In [67]:
serr

b    3
d    4
e    5
Name: o, dtype: int32

In [68]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [69]:
frame - serr

b  d  e
U -3 -3 -3
o  0  0  0
t  3  3  3
r  6  6  6

In [70]:
# 全部都减

In [71]:
serr2 = pd.Series(range(3),index=['b','e','f])

SyntaxError: EOL while scanning string literal (<ipython-input-71-3d495b679940>, line 1)

In [72]:
serr2 = pd.Series(np.arange(3),index=['b','e','f])

SyntaxError: EOL while scanning string literal (<ipython-input-72-407b4ebf2856>, line 1)

In [73]:
series2 = pd.Series(range(3), index=['b', 'e', 'f']) 

In [74]:
serr2 = pd.Series(np.arange(3),index=['b','e','f])

SyntaxError: EOL while scanning string literal (<ipython-input-74-407b4ebf2856>, line 1)

In [75]:
serr2 = pd.Series(np.arange(3),index=['b','e','f])

SyntaxError: EOL while scanning string literal (<ipython-input-75-407b4ebf2856>, line 1)

In [76]:
serr2 = pd.Series(np.arange(3),index=['b','e','f'])

In [77]:
serr2

b    0
e    1
f    2
dtype: int32

In [78]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [79]:
serr2

b    0
e    1
f    2
dtype: int32

In [80]:
frame + serr2

b   d     e   f
U  0.0 NaN   3.0 NaN
o  3.0 NaN   6.0 NaN
t  6.0 NaN   9.0 NaN
r  9.0 NaN  12.0 NaN

In [81]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [82]:
serr2

b    0
e    1
f    2
dtype: int32

In [83]:
ser1 = frame['d']

In [84]:
ser1

U     1
o     4
t     7
r    10
Name: d, dtype: int32

In [85]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [86]:
frame + ser1

U   b   d   e   o   r   t
U NaN NaN NaN NaN NaN NaN NaN
o NaN NaN NaN NaN NaN NaN NaN
t NaN NaN NaN NaN NaN NaN NaN
r NaN NaN NaN NaN NaN NaN NaN

In [87]:
ser1

U     1
o     4
t     7
r    10
Name: d, dtype: int32

In [88]:
frame.add(ser1)

U   b   d   e   o   r   t
U NaN NaN NaN NaN NaN NaN NaN
o NaN NaN NaN NaN NaN NaN NaN
t NaN NaN NaN NaN NaN NaN NaN
r NaN NaN NaN NaN NaN NaN NaN

In [89]:
frame.sub(ser1)

U   b   d   e   o   r   t
U NaN NaN NaN NaN NaN NaN NaN
o NaN NaN NaN NaN NaN NaN NaN
t NaN NaN NaN NaN NaN NaN NaN
r NaN NaN NaN NaN NaN NaN NaN

In [90]:
frame.sub(ser1,axis = 'index')

b  d  e
U -1  0  1
o -1  0  1
t -1  0  1
r -1  0  1

In [91]:
frame.add(ser1,axis='index')

b   d   e
U   1   2   3
o   7   8   9
t  13  14  15
r  19  20  21

In [92]:
frame

b   d   e
U  0   1   2
o  3   4   5
t  6   7   8
r  9  10  11

In [93]:
frame.add(ser1,axis=0)

b   d   e
U   1   2   3
o   7   8   9
t  13  14  15
r  19  20  21

In [94]:
frame.add(ser1)

U   b   d   e   o   r   t
U NaN NaN NaN NaN NaN NaN NaN
o NaN NaN NaN NaN NaN NaN NaN
t NaN NaN NaN NaN NaN NaN NaN
r NaN NaN NaN NaN NaN NaN NaN

In [95]:
# 上述方法中，默认axis = 1 ，即在列上进行广播（列上扩展）

In [96]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['U','O','T','R'])

In [97]:
frame

b         d         e
U -0.141505 -0.653775 -0.857825
O  0.103103 -0.073780 -0.549774
T  1.853536  0.924655 -1.778463
R -0.664708  0.083743 -1.661595

In [98]:
np.abs(frame)

b         d         e
U  0.141505  0.653775  0.857825
O  0.103103  0.073780  0.549774
T  1.853536  0.924655  1.778463
R  0.664708  0.083743  1.661595

In [99]:
# 一个常见的操作是：将函数应用到由各列或各行组成的一维数组上

In [100]:
f = lambda x: x.max() - x.min()

In [101]:
frame.apply(f)

b    2.518244
d    1.578430
e    1.228689
dtype: float64

In [102]:
frame

b         d         e
U -0.141505 -0.653775 -0.857825
O  0.103103 -0.073780 -0.549774
T  1.853536  0.924655 -1.778463
R -0.664708  0.083743 -1.661595

In [103]:
frame.apply(f,axis = 0)

b    2.518244
d    1.578430
e    1.228689
dtype: float64

In [104]:
frame.apply(f,axis = 1)

U    0.716320
O    0.652878
T    3.631999
R    1.745338
dtype: float64

In [105]:
# 排序和排名

In [106]:
# 根据条件对数据集排序

In [107]:
obj = pd.Series(range(4),index=['d','a','c','b'])

In [108]:
obj

d    0
a    1
c    2
b    3
dtype: int64

In [109]:
obj.sort_index()

a    1
b    3
c    2
d    0
dtype: int64

In [110]:
obj.sort_values

<bound method Series.sort_values of d    0
a    1
c    2
b    3
dtype: int64>

In [111]:
obj.sort_values()

d    0
a    1
c    2
b    3
dtype: int64

In [112]:
# 对于 DF 可以根据任意一个轴上的索引进行排序

In [113]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['one','two'],columns=['a','b','c','d'])

In [114]:
frame

a  b  c  d
one  0  1  2  3
two  4  5  6  7

In [115]:
frame.sort_index()

a  b  c  d
one  0  1  2  3
two  4  5  6  7

In [116]:
frame.sort_index(axis=1)

a  b  c  d
one  0  1  2  3
two  4  5  6  7

In [117]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['tow','one'],columns=['b','a','c','d'])

In [118]:
frame

b  a  c  d
tow  0  1  2  3
one  4  5  6  7

In [119]:
frame.sort_index()

b  a  c  d
one  4  5  6  7
tow  0  1  2  3

In [120]:
frame.sort_index(axis=1)

a  b  c  d
tow  1  0  2  3
one  5  4  6  7

In [121]:
# 使用降序排列 

In [122]:
frame.sort_index(axis = 1, ascending=False)

d  c  b  a
tow  3  2  0  1
one  7  6  4  5

In [123]:
frame.sort_values()

TypeError: sort_values() missing 1 required positional argument: 'by'

In [124]:
frame.sort_values(by = 'b',ascending=False)

b  a  c  d
one  4  5  6  7
tow  0  1  2  3

In [125]:
frame.sort_values(by = ['b','a'],ascending=False)

b  a  c  d
one  4  5  6  7
tow  0  1  2  3

In [ ]:
# axis = 0 Index 为轴， axis = 1 columns 位轴，哪个为轴，哪个在动