In [1]:
# 第七章，数据清洗和准备

In [2]:
# 处理缺失数据

In [3]:
# 对于数值数据，pandas 使用浮点值 Nan（not a number） 表示缺失数据

In [4]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado']) 

NameError: name 'pd' is not defined

In [5]:
import pandas as pd 

In [6]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado']) 

NameError: name 'np' is not defined

In [7]:
import numpy as np

In [8]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado']) 

In [9]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [10]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [11]:
# 数据清洗常用函数

In [12]:
# dropna 

In [13]:
from numpy import nan as NA

In [14]:
data = pd.Series([1,NA,3.5,NA,7])

In [15]:
data.dropna

<bound method Series.dropna of 0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64>

In [16]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [17]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [18]:
# 前者等价于 data[data.notnull()]

In [19]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [20]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],    ....:                      [NA, NA, NA], [NA, 6.5, 3.]])

SyntaxError: invalid syntax (<ipython-input-20-7e32d04d4f1b>, line 1)

In [21]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [22]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [24]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [25]:
# 对于 DF 对象而言，dropna 默认丢弃任何含有缺失值的行

In [26]:
#关键之key ：  how = 'all'  则丢弃全为 NA 的那些行

In [27]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [28]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [29]:
data[4] = NA

In [30]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [31]:
data[0]

0    1.0
1    1.0
2    NaN
3    NaN
Name: 0, dtype: float64

In [32]:
data['0']

KeyError: '0'

In [33]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [34]:
data.loc('1')

ValueError: No axis named 1 for object type <class 'pandas.core.frame.DataFrame'>

In [35]:
data.iloc(1)

In [36]:
df = pd.DataFrame(np.random.rand(7,3))

In [37]:
df

0         1         2
0  0.328283  0.444738  0.585662
1  0.724772  0.951039  0.254991
2  0.113781  0.031494  0.294877
3  0.717706  0.858877  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [38]:
df.iloc[:4,1
    ]

0    0.444738
1    0.951039
2    0.031494
3    0.858877
Name: 1, dtype: float64

In [39]:
df[:4,1] = NA

TypeError: unhashable type: 'slice'

In [40]:
df

0         1         2
0  0.328283  0.444738  0.585662
1  0.724772  0.951039  0.254991
2  0.113781  0.031494  0.294877
3  0.717706  0.858877  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [41]:
df.iloc[:4,1] = NA

In [42]:
df

0         1         2
0  0.328283       NaN  0.585662
1  0.724772       NaN  0.254991
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [43]:
df[:2,2] = NA

TypeError: unhashable type: 'slice'

In [44]:
df.iloc[:2,2]

0    0.585662
1    0.254991
Name: 2, dtype: float64

In [45]:
df.iloc[:2,2] = NA

In [46]:
df

0         1         2
0  0.328283       NaN       NaN
1  0.724772       NaN       NaN
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [47]:
df.dropna()

0         1         2
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [48]:
df.dropna(thresh=2)

0         1         2
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [49]:
df.dropna(thresh=1)

0         1         2
0  0.328283       NaN       NaN
1  0.724772       NaN       NaN
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [50]:
df.dropna(thresh=3)

0         1         2
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [56]:
# thresh = n  只保留至少有 n 个 非NA  的 行/ 列

In [52]:
df

0         1         2
0  0.328283       NaN       NaN
1  0.724772       NaN       NaN
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [53]:
df.dropna(thresh = 2)

0         1         2
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [54]:
df.dropna(thresh=3)

0         1         2
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [55]:
df.dropna(thresh=1)

0         1         2
0  0.328283       NaN       NaN
1  0.724772       NaN       NaN
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [57]:
df

0         1         2
0  0.328283       NaN       NaN
1  0.724772       NaN       NaN
2  0.113781       NaN  0.294877
3  0.717706       NaN  0.661561
4  0.646260  0.952793  0.809609
5  0.133804  0.350648  0.844127
6  0.205576  0.698771  0.975143

In [58]:
df = pd.DataFrame(np.random.randn(16).reshape((4,4)))

In [59]:
df

0         1         2         3
0  0.903519  0.947579  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050 -0.650639 -0.025056 -3.211267
3 -0.621236  1.254811 -0.641855  0.504777

In [60]:
df.iloc[:1,:2] = NA

In [61]:
df

0         1         2         3
0       NaN       NaN  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050 -0.650639 -0.025056 -3.211267
3 -0.621236  1.254811 -0.641855  0.504777

In [62]:
df.iloc[2,1:4] = NA

In [63]:
df

0         1         2         3
0       NaN       NaN  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050       NaN       NaN       NaN
3 -0.621236  1.254811 -0.641855  0.504777

In [64]:
df.dropna(thresh=2)

0         1         2         3
0       NaN       NaN  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
3 -0.621236  1.254811 -0.641855  0.504777

In [65]:
df.dropna(thresh=3)

0         1         2         3
1  1.347069 -0.609050 -1.627597 -1.023284
3 -0.621236  1.254811 -0.641855  0.504777

In [66]:
# 填充缺失数据

In [67]:
df

0         1         2         3
0       NaN       NaN  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050       NaN       NaN       NaN
3 -0.621236  1.254811 -0.641855  0.504777

In [68]:
df.fillna(0)

0         1         2         3
0  0.000000  0.000000  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050  0.000000  0.000000  0.000000
3 -0.621236  1.254811 -0.641855  0.504777

In [69]:
df

0         1         2         3
0       NaN       NaN  1.618483 -0.511223
1  1.347069 -0.609050 -1.627597 -1.023284
2 -1.206050       NaN       NaN       NaN
3 -0.621236  1.254811 -0.641855  0.504777

In [70]:
df.iloc[:2,2] = NA

In [71]:
df

0         1         2         3
0       NaN       NaN       NaN -0.511223
1  1.347069 -0.609050       NaN -1.023284
2 -1.206050       NaN       NaN       NaN
3 -0.621236  1.254811 -0.641855  0.504777

In [72]:
# 如果通过一个字典调用 fillna 就可以实现对不通过的列填充不同的值

In [73]:
df

0         1         2         3
0       NaN       NaN       NaN -0.511223
1  1.347069 -0.609050       NaN -1.023284
2 -1.206050       NaN       NaN       NaN
3 -0.621236  1.254811 -0.641855  0.504777

In [74]:
df.fillna({1:5,2:6,3:9})

0         1         2         3
0       NaN  5.000000  6.000000 -0.511223
1  1.347069 -0.609050  6.000000 -1.023284
2 -1.206050  5.000000  6.000000  9.000000
3 -0.621236  1.254811 -0.641855  0.504777

In [75]:
# 返回新的对象，使用inplace 参数可以对现有的对象进行修改

In [76]:
# 移除重复数据

In [77]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],                      'k2': [1, 1, 2, 3, 3, 4, 4]}) 

In [78]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [79]:
# DataFrame 的 duplicated 方法返回一个布尔型 Series 表示各行是否重复

In [80]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [81]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [82]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [83]:
# 利用函数或映射进行数据转换

In [84]:
 data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',                               'Pastrami', 'corned beef', 'Bacon',                                  'pastrami', 'honey ham', 'nova 
lox'],                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

SyntaxError: EOL while scanning string literal (<ipython-input-84-fb6f5da6e6a4>, line 1)

In [85]:
 data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',  'Pastrami', 'corned beef', 'Bacon'， 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

SyntaxError: invalid character in identifier (<ipython-input-85-12836322ec09>, line 1)

In [86]:
 data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',  'Pastrami', 'corned beef', 'Bacon'， 'pastrami', 'honeyham', 'novalox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

SyntaxError: invalid character in identifier (<ipython-input-86-c56a35723687>, line 1)

In [87]:
 data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',  'Pastrami', 'corned beef', 'Bacon'， 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6 ]})    

SyntaxError: invalid character in identifier (<ipython-input-87-163c996c16d1>, line 1)

In [88]:
data = pd.DataFrame({'food':['ba','pu le','bacon','past','corner','Bacs','pas','honey ham','nov lox'],'ouc':[4,3,12,6,7.5,8,3,5,6]})

In [89]:
data

food   ouc
0         ba   4.0
1      pu le   3.0
2      bacon  12.0
3       past   6.0
4     corner   7.5
5       Bacs   8.0
6        pas   3.0
7  honey ham   5.0
8    nov lox   6.0

In [90]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],'ouc':[4,3,12,6,7.5,8,3,5,6]})

In [91]:
data

food   ouc
0        bacon   4.0
1  pulled pork   3.0
2        bacon  12.0
3     Pastrami   6.0
4  corned beef   7.5
5        Bacon   8.0
6     pastrami   3.0
7    honey ham   5.0
8     nova lox   6.0

In [92]:
# 添加一列表示该肉类食物来源的动物类型，先编写一个不同肉类到动物的映射

In [93]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami ':'cow',
    'corned beef ':'cow',
    'honey ham':'pig',
    'nova lox':'salmon',
}

In [94]:
# Series 的 map 方法可以接受一个函数或含有映射关系的字典型对象

In [95]:
lowercased = data['food'].str.lower()

In [96]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [97]:
# Series.str.lower()方法，转为小写

In [98]:
data['animal'] = lowercased.map(meat_to_animal)

In [99]:
data

food   ouc  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  12.0     pig
3     Pastrami   6.0     NaN
4  corned beef   7.5     NaN
5        Bacon   8.0     pig
6     pastrami   3.0     NaN
7    honey ham   5.0     pig
8     nova lox   6.0  salmon

In [100]:
# 也可以传入一个能够完成全部这些工作的函数

In [101]:
data['food'].map(lambda x : meat_to_animal[x.lower])

KeyError: <built-in method lower of str object at 0x0000022284F8B7D8>

In [103]:
data['food'].map(lambda x : meat_to_animal[x.lower()])

KeyError: 'pastrami'

In [104]:

data['food'].map(lambda x : meat_to_animal[x.lower()])

KeyError: 'pastrami'

In [105]:
data['animal'] = lowercased.map(meat_to_animal)

In [106]:
data

food   ouc  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  12.0     pig
3     Pastrami   6.0     NaN
4  corned beef   7.5     NaN
5        Bacon   8.0     pig
6     pastrami   3.0     NaN
7    honey ham   5.0     pig
8     nova lox   6.0  salmon

In [107]:
del data['animal']

In [108]:
data

food   ouc
0        bacon   4.0
1  pulled pork   3.0
2        bacon  12.0
3     Pastrami   6.0
4  corned beef   7.5
5        Bacon   8.0
6     pastrami   3.0
7    honey ham   5.0
8     nova lox   6.0

In [109]:
data['animal'] = lowercased.map(lambda x: meat_to_animal[x.lower()])

KeyError: 'pastrami'

In [110]:
data['animal'] = lowercased.map(meat_to_animal)

In [111]:
data

food   ouc  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  12.0     pig
3     Pastrami   6.0     NaN
4  corned beef   7.5     NaN
5        Bacon   8.0     pig
6     pastrami   3.0     NaN
7    honey ham   5.0     pig
8     nova lox   6.0  salmon

In [112]:
del data['animal']

In [113]:
data

food   ouc
0        bacon   4.0
1  pulled pork   3.0
2        bacon  12.0
3     Pastrami   6.0
4  corned beef   7.5
5        Bacon   8.0
6     pastrami   3.0
7    honey ham   5.0
8     nova lox   6.0

In [114]:
data['food'].map(lambda x : meat_to_animal[x.lower()])

KeyError: 'pastrami'

In [115]:
data

food   ouc
0        bacon   4.0
1  pulled pork   3.0
2        bacon  12.0
3     Pastrami   6.0
4  corned beef   7.5
5        Bacon   8.0
6     pastrami   3.0
7    honey ham   5.0
8     nova lox   6.0

In [116]:
data['animal'] = lowercased.map(meat_to_animal)

In [117]:
daa

NameError: name 'daa' is not defined

In [118]:
data

food   ouc  animal
0        bacon   4.0     pig
1  pulled pork   3.0     pig
2        bacon  12.0     pig
3     Pastrami   6.0     NaN
4  corned beef   7.5     NaN
5        Bacon   8.0     pig
6     pastrami   3.0     NaN
7    honey ham   5.0     pig
8     nova lox   6.0  salmon

In [119]:
meat_to_animal

{'bacon': 'pig',
 'corned beef ': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami ': 'cow',
 'pulled pork': 'pig'}

In [120]:
Pastrami pastrami

SyntaxError: invalid syntax (<ipython-input-120-b423a7abbf06>, line 1)

In [121]:
# map 是一种实现元素级转化以及其他数据清理工作的边界方式

In [122]:
data = pd.Series([1.,-999.,2.,-999.,-1000,3.])

In [123]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [124]:
# -999 可能是一个表示确实数据的标记值

In [125]:
# replace

In [126]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [127]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [128]:
# 一次替换多个值

In [129]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [130]:
# 要让每个值有不同的替换值，可以传递一个替换列表

In [131]:
data.replace([-999,-1000],[np.nan,6666])

0       1.0
1       NaN
2       2.0
3       NaN
4    6666.0
5       3.0
dtype: float64

In [132]:
# 传入的数据是字典的时候

In [133]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [134]:
# 重命名轴索引

In [135]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['o','co','new'],columns=['one','two','three','four'])

In [136]:
transform = lambda x:x[:4].upper()

In [137]:
data.index.map(transform)

Index(['O', 'CO', 'NEW'], dtype='object')

In [138]:
data

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [139]:
transform = lambda x:x[:1].upper()

In [140]:
data.index.map(transform)

Index(['O', 'C', 'N'], dtype='object')

In [141]:
data

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [142]:
data.index = data.index.map(transform)

In [143]:
data

one  two  three  four
O    0    1      2     3
C    4    5      6     7
N    8    9     10    11

In [144]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['o','co','new'],columns=['one','two','three','four'])

In [145]:
data

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [146]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
O      0    1      2     3
Co     4    5      6     7
New    8    9     10    11

In [147]:
# rename 可以结合字典型对象对部分轴标签进行更新

In [148]:
data.rename(index ={'O'}:'HAHHA',columns={'FOUR'}:{'YJH'})

SyntaxError: invalid syntax (<ipython-input-148-6c1fa815f7da>, line 1)

In [149]:
data.rename(index ={'O':'HAHHA'},columns={'FOUR':'YJH'})

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [150]:
data

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [151]:
data.rename(index ={'o':'HAHHA'},columns={'four':'YJH'})

one  two  three  YJH
HAHHA    0    1      2    3
co       4    5      6    7
new      8    9     10   11

In [152]:
data

one  two  three  four
o      0    1      2     3
co     4    5      6     7
new    8    9     10    11

In [153]:
data = data.rename(index ={'o':'HAHHA'},columns={'four':'YJH'})

In [154]:
data

one  two  three  YJH
HAHHA    0    1      2    3
co       4    5      6    7
new      8    9     10   11

In [155]:
# 离散化和面元划分

In [156]:
age  = [20,25,66,26,95,36,22,19,55,44]

In [157]:
bin = [18,25,35,60,10]

In [158]:
cats = pd.cut(age, bin)

ValueError: bins must increase monotonically.

In [159]:
bin = [18,25,35,60,100]

In [160]:
cats = pd.cut(age,bin)

In [161]:
cats

[(18, 25], (18, 25], (60, 100], (25, 35], (60, 100], (35, 60], (18, 25], (18, 25], (35, 60], (35, 60]]
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [162]:
cats.codes()

TypeError: 'numpy.ndarray' object is not callable

In [163]:
cats.code()

AttributeError: 'Categorical' object has no attribute 'code'

In [164]:
cats.codes

array([0, 0, 3, 1, 3, 2, 0, 0, 2, 2], dtype=int8)

In [165]:
pd.value_counts(cats)

(18, 25]     4
(35, 60]     3
(60, 100]    2
(25, 35]     1
dtype: int64

In [166]:
# 传递一个列表到labesl设置直接的面元名称

In [167]:
# 如果想 cut 传入的是面元数量而不是确定的面元边界，则它会根据数据的最小值和最大值计算等长面元

In [168]:
data = np.random.rand(20)

In [169]:
data

array([0.65121352, 0.96461552, 0.58242016, 0.0224836 , 0.1162227 ,
       0.4401711 , 0.34472006, 0.6403771 , 0.68986243, 0.49644759,
       0.13347625, 0.0169221 , 0.52293416, 0.97308749, 0.11398324,
       0.5657011 , 0.63509202, 0.35995345, 0.76267076, 0.54210177])

In [170]:
pd.cut(data,4,precision=2)

[(0.5, 0.73], (0.73, 0.97], (0.5, 0.73], (0.016, 0.26], (0.016, 0.26], ..., (0.5, 0.73], (0.5, 0.73], (0.26, 0.5], (0.73, 0.97], (0.5, 0.73]]
Length: 20
Categories (4, interval[float64]): [(0.016, 0.26] < (0.26, 0.5] < (0.5, 0.73] < (0.73, 0.97]]

In [171]:
ca = pd.cut(data,4,precision=2)

In [172]:
pd.value_counts(ca)

(0.5, 0.73]      9
(0.016, 0.26]    5
(0.73, 0.97]     3
(0.26, 0.5]      3
dtype: int64

In [173]:
caa = pd.qcut(data,4,precision=2)

In [174]:
caa

[(0.64, 0.97], (0.64, 0.97], (0.53, 0.64], (0.007000000000000001, 0.29], (0.007000000000000001, 0.29], ..., (0.53, 0.64], (0.53, 0.64], (0.29, 0.53], (0.64, 0.97], (0.53, 0.64]]
Length: 20
Categories (4, interval[float64]): [(0.007000000000000001, 0.29] < (0.29, 0.53] < (0.53, 0.64] < (0.64, 0.97]]

In [175]:
pd.value_counts(caa)

(0.64, 0.97]                    5
(0.53, 0.64]                    5
(0.29, 0.53]                    5
(0.007000000000000001, 0.29]    5
dtype: int64

In [176]:
# 检测和过滤异常值

In [178]:
# 过滤和变化异常值(outlier) 在很大程度上就是运用数组运算

In [179]:
data = pd.DataFrame(np.random.randn(1000,4))

In [180]:
data

0         1         2         3
0   -0.504634 -0.660010 -3.850211 -0.374160
1   -0.316117  1.459958  0.405335  0.803601
2   -0.344460 -0.470620  1.852126 -1.334857
3    1.966024 -1.550935 -1.025969 -1.197039
4   -0.054121 -0.417634 -0.262562  0.161495
5    0.584731 -0.399414 -1.359770  0.230564
6    0.569706 -0.796591  1.701752 -2.123892
7    1.320260  0.630134  0.073129 -2.050811
8   -0.741899 -0.270440 -0.494451  0.970515
9    0.459865 -0.734652 -0.128484  0.408000
10   2.287598 -1.809706  0.221583 -1.130724
11  -0.682462  0.395989  0.110056 -0.024483
12  -2.157025 -1.144355 -0.102027  0.888398
13   0.470013  0.582277 -0.079648  0.076398
14  -1.256514  0.808466 -0.456336  1.587948
15   0.569587  0.637198  0.020987 -0.472309
16  -1.489410  0.075896 -1.608676  0.588947
17   0.460076  0.068003 -0.797887 -0.495798
18  -0.915984  1.496047  1.541167 -0.718651
19  -0.813548  0.379697  1.360748  1.644417
20   0.679941 -1.017655 -1.794034 -0.061525
21  -0.314079 -1.378073 -0.279297  0.218133
22   0.178473  1.834103  1.196556  1.471383
23   0.336024  1.151476 -1.072537 -0.741405
24   1.005885  2.046530 -0.876038  0.035591
25  -0.359911  0.430934 -1.297296 -0.095698
26   0.624211  1.574955 -0.665766 -0.042845
27   0.519054 -0.497797  1.470158  1.668663
28  -0.675122 -0.472850 -0.007115 -1.910228
29  -0.026425  0.670043 -1.285204 -1.551883
..        ...       ...       ...       ...
970  1.159500 -0.365181  1.326721  1.368619
971  1.031186  1.240212  0.143554  1.505138
972 -1.234787  1.742447 -0.747707  0.531940
973  0.985884  1.723245  0.357854  0.089574
974 -0.067486 -0.113423 -1.534740 -1.168918
975  1.099415 -0.823152  0.907164  1.422687
976  0.785765 -1.345927 -1.259338  1.043372
977 -0.686808  0.004901  2.479118 -1.481341
978 -1.358252 -0.745900  1.219143  0.946494
979  0.032840  0.402456 -1.106553  0.152920
980  2.250155  0.595606  0.437862  0.681149
981 -1.710960 -1.238453  3.482960 -1.106496
982  0.251087 -0.541284  0.943980  0.951703
983 -0.418727  0.889821 -0.918625  0.391411
984  1.527571 -0.954434 -0.761988 -0.445748
985 -0.240392 -0.217037 -0.705953  0.002310
986  0.042908  0.623814  0.142893  0.026956
987 -1.128102  0.279824 -1.122935 -0.493069
988  1.640571 -1.108239  2.077397  0.054522
989  1.661441 -0.637270 -1.771998 -0.794214
990  0.212292  0.633915 -1.951415  0.787232
991 -0.991965 -0.248665 -0.502836  0.648688
992  0.896921 -0.970596 -1.027264  0.950206
993  0.799077 -0.433245 -0.125623 -0.613962
994  1.736200  0.816346 -0.772030 -1.971150
995  2.675491 -0.881616 -0.834694 -0.831682
996 -1.371670 -0.484282  0.691795  0.575607
997  0.896118  0.172989  0.931981  0.876225
998  1.731909  2.122078 -0.314193 -0.588584
999 -0.003104  0.723831  0.672164 -0.535566

[1000 rows x 4 columns]

In [181]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017965     0.086231    -0.005298     0.021799
std       1.025705     1.005315     1.029394     1.016316
min      -3.432116    -3.133130    -3.850211    -2.745235
25%      -0.713446    -0.564394    -0.718791    -0.657942
50%       0.015270     0.089232    -0.064209     0.011589
75%       0.706463     0.749729     0.668322     0.701115
max       2.892917     3.450546     4.266567     2.986400

In [182]:
# 假设想要找出某列重绝对值大小超过3的值

In [183]:
col =data[2]

In [184]:
col

0     -3.850211
1      0.405335
2      1.852126
3     -1.025969
4     -0.262562
5     -1.359770
6      1.701752
7      0.073129
8     -0.494451
9     -0.128484
10     0.221583
11     0.110056
12    -0.102027
13    -0.079648
14    -0.456336
15     0.020987
16    -1.608676
17    -0.797887
18     1.541167
19     1.360748
20    -1.794034
21    -0.279297
22     1.196556
23    -1.072537
24    -0.876038
25    -1.297296
26    -0.665766
27     1.470158
28    -0.007115
29    -1.285204
         ...   
970    1.326721
971    0.143554
972   -0.747707
973    0.357854
974   -1.534740
975    0.907164
976   -1.259338
977    2.479118
978    1.219143
979   -1.106553
980    0.437862
981    3.482960
982    0.943980
983   -0.918625
984   -0.761988
985   -0.705953
986    0.142893
987   -1.122935
988    2.077397
989   -1.771998
990   -1.951415
991   -0.502836
992   -1.027264
993   -0.125623
994   -0.772030
995   -0.834694
996    0.691795
997    0.931981
998   -0.314193
999    0.672164
Name: 2, Length: 1000, d

In [185]:
col[np.abs(col) > 3]

0     -3.850211
173    4.266567
259    3.207105
831    3.045635
981    3.482960
Name: 2, dtype: float64

In [186]:
# 要选出全部含有“超过3或者-3”的行，可以在布尔型 DF 中使用 any

In [187]:
data[(np.abs(col)>3).any(1)]

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>

In [188]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
0   -0.504634 -0.660010 -3.850211 -0.374160
38  -1.107840 -3.045996 -0.829840 -1.061721
173 -1.412503  1.098639  4.266567 -0.261489
241  0.246093 -3.133130 -1.455100  0.358921
259 -1.094188  0.157413  3.207105  2.246413
343 -0.902016 -3.059374 -1.261204  0.854149
476 -3.432116 -1.163707  0.231457 -1.127962
579 -3.049973  0.859133 -0.755638  0.594612
761  1.483935 -3.061223  0.049779  0.193973
831 -1.976493  0.708209  3.045635  0.469660
939 -0.699392  3.450546 -1.470381  0.817353
981 -1.710960 -1.238453  3.482960 -1.106496

In [189]:
# 排列和随机采样

In [190]:
# 利用 numpy.random.permutation 函数可以轻松实现对 Series 或 DF 的列的排列工作

In [191]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5,4)))

In [192]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [193]:
sample = np.random.permutation(5)

In [194]:
sample

array([2, 4, 0, 3, 1])

In [195]:
sample = np.random.permutation(5)

In [196]:
sample

array([3, 4, 1, 2, 0])

In [197]:
df.taker(sample)

AttributeError: 'DataFrame' object has no attribute 'taker'

In [198]:
df.take(sample
    )

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [199]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [200]:
df.take(sample)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [201]:
sample

array([3, 4, 1, 2, 0])

In [202]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [203]:
df.take(sample)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [204]:
df.iloc(sample)

TypeError: unhashable type: 'numpy.ndarray'

In [205]:
df.iloc([sample])

TypeError: unhashable type: 'list'

In [206]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [207]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3

In [208]:
sample = np.random.permutation(5)

In [209]:
sample

array([1, 2, 3, 4, 0])

In [210]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11

In [211]:
# 另一种常用于统计建模或者机器学习的转换方式是：将分类变量（categorical variable ）转换为‘哑变量’ 或‘指针矩阵’

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],'datla':range(6)})

In [4]:
df

key  datla
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [5]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [6]:
dum = pd.get_dummies(df['key'],prefix='key')

In [7]:
dum

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [8]:
df_with_dumy = df['datal'].jion(dum)

KeyError: 'datal'

In [9]:
df_with_dummy = df[['datal']].join(dum)

KeyError: "['datal'] not in index"

In [10]:
df

key  datla
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [11]:
df_woth_dummy = df[['datla']].join(dum)

In [12]:
df_woth_dummy

datla  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [13]:
# 字符串操作

In [14]:
# 以逗号分隔的字符串可以用 split 拆分成数段

In [15]:
val = 'a,bb,   uduad'

In [16]:
val.split(',')

['a', 'bb', '   uduad']

In [17]:
pieces = [x.strip() for x in val.split(',')]

In [18]:
pieces

['a', 'bb', 'uduad']

In [19]:
first, second, last = pieces

In [20]:
first

'a'

In [21]:
first + ';;' + second + ';;' + last

'a;;bb;;uduad'

In [22]:
pieces

['a', 'bb', 'uduad']

In [23]:
'::'.jion(pieces)

AttributeError: 'str' object has no attribute 'jion'

In [24]:
'::'.join(pieces)

'a::bb::uduad'

In [25]:
'dada'.join(pieces)

'adadabbdadauduad'

In [26]:
val

'a,bb,   uduad'

In [27]:
val.index(':')

ValueError: substring not found

In [28]:
val.find(':')

-1

In [29]:
'a' in val

True

In [30]:
'hah' in val

False

In [31]:
# count 可以返回出现次数， find  index 可以查看子串是否在母串中  in 也可以判断

In [32]:
# replace 通过传入空字符串，用于删除模式

In [33]:
# 正则表达式

In [34]:
# re 模块负责对字符串应用正则表达式

In [35]:
# re 模块 3 大类，模式匹配，替换，和拆分

In [36]:
import re

In [37]:
text = " foo   bar\t   baz    \tqux"

In [38]:
text

' foo   bar\t   baz    \tqux'

In [39]:
re.split('\s+',text)

['', 'foo', 'bar', 'baz', 'qux']

In [40]:
regex = re.compile('\s+')

In [41]:
regex

re.compile(r'\s+', re.UNICODE)

In [42]:
regex.split(text)

['', 'foo', 'bar', 'baz', 'qux']

In [43]:
regex.findall(text)

[' ', '   ', '\t   ', '    \t']

In [44]:
# 如想避免正则表达式中不需要的转义，在原始字符串的   r'****'

In [45]:
# 如果打算对许多字符串应用同一条正则表达式，强烈建议通过re.compile 创建 regex 对象，可以节省大量的 cpu 

In [46]:
text = """Dave dave@google.com

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-46-7a584bde3d84>, line 1)

In [4]:
text = """Dave dave@google.com
Steve steve@google.com
Haha haha@google.com
Ryan ryan@yahoo.com
"""

In [48]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\[A-Z](2.4)'

In [49]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\[A-Z](2,4)'

In [50]:
regex = re.complie(pattern,flags=re.IGNORECASE)

AttributeError: module 're' has no attribute 'complie'

In [51]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [52]:
regex.findall(text)

[]

In [53]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z](2,4)'

In [54]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [55]:
regex

re.compile(r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z](2,4)', re.IGNORECASE|re.UNICODE)

In [56]:
regex.findall(text)

[]

In [57]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [58]:
re.compile(pattern,flags=re.IGNORECASE)

re.compile(r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}', re.IGNORECASE|re.UNICODE)

In [59]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [60]:
regex.findall(text)

['dave@google.com', 'steve@google.com', 'haha@google.com', 'ryan@yahoo.com']

In [61]:
# search 则放回第一个邮箱地址

In [62]:
m = regex.search(text)

In [63]:
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [64]:
print(m)

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>


In [65]:
print(regex.search(text))

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>


In [66]:
# sub 方法可以将匹配到的模式替换为指定字符串

In [67]:
print(regex.sub('hahhahahaha',text))

Dave hahhahahaha
Steve hahhahahaha
Haha hahhahahaha
Ryan hahhahahaha



In [68]:
#  如果不仅想找出电子邮箱地址，还想将各个地址分成 3 个部分： 用户名，域名以及后缀。要实现此功能，只需要将待分段的模式的各部分用圆括号抱起来即可

In [69]:
a = np.arange(2)

In [70]:
a

array([0, 1])

In [71]:
a = np.arange(2)

In [72]:
a

array([0, 1])

In [73]:
a = np.arange(2)

In [74]:
a

array([0, 1])

In [1]:
import numpy as np 

In [2]:
import pandas as pd

In [3]:
import re

In [5]:
text

'Dave dave@google.com\nSteve steve@google.com\nHaha haha@google.com\nRyan ryan@yahoo.com\n'

In [6]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-])+\.([A-Z]{2,4})'

In [7]:
regex = re.compile(pattern,flags = re.IGNORECASE)

In [8]:
m = regex.match('wesm@bringt.net')

In [9]:
m

<_sre.SRE_Match object; span=(0, 15), match='wesm@bringt.net'>

In [10]:
m.groups()

('wesm', 't', 'net')

In [11]:
# 对于带有分组功能的模块，findall 会返回一个元组列表

In [12]:
regex.findall(text)

[('dave', 'e', 'com'),
 ('steve', 'e', 'com'),
 ('haha', 'e', 'com'),
 ('ryan', 'o', 'com')]

In [13]:
# pandas 的矢量化字符串函数

In [14]:
 data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',        'Rob': 'rob@gmail.com', 'Wes': np.nan} 

In [15]:
dat

NameError: name 'dat' is not defined

In [16]:
data

{'Dave': 'dave@google.com',
 'Rob': 'rob@gmail.com',
 'Steve': 'steve@gmail.com',
 'Wes': nan}

In [17]:
data = pd.Series(data)

In [18]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [19]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [20]:
# 通过data.map 所有字符串和正则表达式方法都能被应用于（传入lambda表达式或其他函数）

In [21]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-])+\\.([A-Z]{2,4})'

In [22]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave      [(dave, e, com)]
Steve    [(steve, l, com)]
Rob        [(rob, l, com)]
Wes                    NaN
dtype: object

In [23]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [24]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [25]:
# Series 有一些能够跳过 NA 值的面向数组方法，进行字符串操作

In [26]:
# 比如 str.contains

In [27]:
 # 矢量化元素获取操作

In [28]:
# 1.str.get      2.   在 str 属性上使用索引

In [29]:
match = data.str.match(pattern,flags=re.IGNORECASE)

In [30]:
match

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [31]:
# 要想访问嵌入列表中的元素，可以传递索引到这两个函数中

In [32]:
match.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [33]:
match

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [34]:
match.str.get(0)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [35]:
match

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [36]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [37]:
data.str.get(1)

Dave       a
Steve      t
Rob        o
Wes      NaN
dtype: object

In [38]:
data.str.get(0)

Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [39]:
data.str.get(-1)

Dave       m
Steve      m
Rob        m
Wes      NaN
dtype: object

In [40]:
# str.get(N)  N 为 str中的提取的字符串的索引

In [41]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [42]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [43]:
data.str.get(:5)

SyntaxError: invalid syntax (<ipython-input-43-287ad8deab3d>, line 1)

In [44]:
# pandas 字符串一些常用方法

In [45]:
# cat

In [46]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [47]:
data.cat('d')

AttributeError: Can only use .cat accessor with a 'category' dtype

In [48]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [49]:
data.cat.categories = list('abcd')

AttributeError: Can only use .cat accessor with a 'category' dtype