In [1]:
# Numpy 最重要的特点之一是N维数组对象 n darry

In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)

In [4]:
data

array([[-1.47568101, -0.3381022 ,  1.35516196],
       [-0.09059499,  1.3909578 ,  0.34731309]])

In [5]:
data *10

array([[-14.75681013,  -3.38102202,  13.55161955],
       [ -0.90594986,  13.90957801,   3.47313089]])

In [6]:
data + data

array([[-2.95136203, -0.6762044 ,  2.71032391],
       [-0.18118997,  2.7819156 ,  0.69462618]])

In [7]:
# ndarray 是一个通用的同构数据多容器，其中所有的元素必须是相同类型的

In [8]:
# 创建ndarray

In [9]:
# 最简单的方法：使用array函数

In [10]:
datal = [6,5,9,53.3]

In [11]:
arr = np.array(datal)

In [12]:
arr

array([ 6. ,  5. ,  9. , 53.3])

In [13]:
data2 = [[1,2,35.30],[5,6,9.5]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[ 1. ,  2. , 35.3],
       [ 5. ,  6. ,  9.5]])

In [16]:
arr.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('float64')

In [19]:
# 除了np.array之外，zeros 和 ones 分别可以 全0 或者 全1 数据

In [20]:
#emety 可以创建空数组

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros([3,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
# dtpye 指定数数据类型 ，也可以查看

In [25]:
arr = np.array([1,2,3],dtype = np.float64)

In [26]:
arr

array([1., 2., 3.])

In [27]:
arr.dtype

dtype('float64')

In [28]:
# object : Python 对象类型

In [29]:
#类型转换：astype

In [30]:
arr = np.array([1,2,3,4,5])

In [31]:
arr.dtype

dtype('int32')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float.arr

AttributeError: type object 'float' has no attribute 'arr'

In [34]:
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
# float 变为 int 型的话， 小数部分将会被截取删除

In [37]:
arr = np.array([3.7,1.20],[2.5,6.6])

TypeError: data type not understood

In [38]:
arr = np.array([3.7,1.2],[2.5,6.6])

TypeError: data type not understood

In [39]:
arr = np.array([[3.7,1.20],[2.5,6.6]])

In [40]:
arr

array([[3.7, 1.2],
       [2.5, 6.6]])

In [41]:
arr.astype(np.int64)

array([[3, 1],
       [2, 6]], dtype=int64)

In [42]:
arr

array([[3.7, 1.2],
       [2.5, 6.6]])

In [43]:
arr

array([[3.7, 1.2],
       [2.5, 6.6]])

In [44]:
arr.astype(np.int64)

array([[3, 1],
       [2, 6]], dtype=int64)

In [45]:
arr.astype(np.int64)

array([[3, 1],
       [2, 6]], dtype=int64)

In [47]:
# 某字符串数组表示的全是数字时候，也可用astype将其换位数值形式，小心用

In [48]:
# 基本的索引和切片

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [53]:
arr[5:8]

array([5, 6, 7])

In [54]:
arr[5:8] = 12

In [55]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [56]:
# 先创建一个切片

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice = 12345

In [60]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [61]:
arr_slice

12345

In [62]:
arr_slice = arr[6:8]

In [63]:
arr_slice

array([12, 12])

In [64]:
arr_slice[1] = 12345

In [65]:
arr

array([    0,     1,     2,     3,     4,    12,    12, 12345,     8,
           9])

In [66]:
arr_slice[0] = 0

In [67]:
arr

array([    0,     1,     2,     3,     4,    12,     0, 12345,     8,
           9])

In [68]:
# 数组的切片是原始数据的视图，意味着数据不是被复制，切片上的修改，源数据也会跟着修改

In [69]:
arr_slice[:] = 999

In [70]:
arr

array([  0,   1,   2,   3,   4,  12, 999, 999,   8,   9])

In [71]:
# 如果只是想要得到ndarray 切片的一份副本而非视图，就要明确进行复制操作，arr[5:8].copy()

In [72]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
arr2

array([[ 1. ,  2. , 35.3],
       [ 5. ,  6. ,  9.5]])

In [74]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr2d(2)

TypeError: 'numpy.ndarray' object is not callable

In [77]:
arr2d[2]

array([7, 8, 9])

In [78]:
arr2d[2][2]

9

In [79]:
arr2d[2,2]

9

In [80]:
# 轴0为行，轴1为列

In [81]:
# 切片索引

In [82]:
arr

array([  0,   1,   2,   3,   4,  12, 999, 999,   8,   9])

In [83]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [84]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:1,:2]

array([[1, 2]])

In [87]:
arr2d([:2,:2])

SyntaxError: invalid syntax (<ipython-input-87-cd56063d41bd>, line 1)

In [88]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
arr2d[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [92]:
# 布尔型索引

In [93]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

In [94]:
data = np.random.randn(7,4)

In [95]:
data

array([[ 1.10728935,  1.65239442,  0.76128641,  0.07411611],
       [ 0.91185355,  1.0882144 , -0.39549824,  0.03088756],
       [ 0.83335794, -1.13334805, -1.36200332, -0.46071419],
       [ 0.8983859 ,  0.29565376, -0.95534284, -0.61847974],
       [ 0.19860081,  0.18504954, -1.27114512,  0.0503359 ],
       [-0.8956616 ,  2.36441263, -0.78104923,  0.28019901],
       [-0.42315023, -0.46089443,  1.0298936 , -0.23436975]])

In [96]:
name

NameError: name 'name' is not defined

In [97]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [98]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [99]:
data[names == 'Bob']

array([[ 1.10728935,  1.65239442,  0.76128641,  0.07411611],
       [ 0.8983859 ,  0.29565376, -0.95534284, -0.61847974]])

In [100]:
data

array([[ 1.10728935,  1.65239442,  0.76128641,  0.07411611],
       [ 0.91185355,  1.0882144 , -0.39549824,  0.03088756],
       [ 0.83335794, -1.13334805, -1.36200332, -0.46071419],
       [ 0.8983859 ,  0.29565376, -0.95534284, -0.61847974],
       [ 0.19860081,  0.18504954, -1.27114512,  0.0503359 ],
       [-0.8956616 ,  2.36441263, -0.78104923,  0.28019901],
       [-0.42315023, -0.46089443,  1.0298936 , -0.23436975]])

In [102]:
# 花式索引，指的是利用整数数组进行索引

In [103]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr2d[2,2]

9

In [105]:
arr2d[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [106]:
# 输入的是一个整数列表

In [107]:
arr2d[[-1,-2]]

array([[7, 8, 9],
       [4, 5, 6]])

In [108]:
arr = np.arange(32)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [110]:
arr.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [111]:
arr.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
arr[[1,5,7,2],[0,3,1,2]]

IndexError: too many indices for array

In [113]:
arr[[1,5,7,2],[0,3,1,2]]

IndexError: too many indices for array

In [114]:
 arr[[1, 5, 7, 2], [0, 3, 1, 2]] 

IndexError: too many indices for array

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [116]:
arr = np.arange(32).reshape((8,4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
 arr[[1, 5, 7, 2], [0, 3, 1, 2]] 

array([ 4, 23, 29, 10])

In [119]:
# 可以将花式索引理解为x ,和 y 值

In [120]:
# 其实，矩阵索引就可以理解为x和y的值

In [121]:
# 属猪的转置和轴对称

In [122]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [123]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [124]:
# 通用函数

In [125]:
arr1 = np.arange(10)

In [126]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [128]:
# sqrt 开方

In [129]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [130]:
arr1.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [131]:
# np.multiply 数组元素相乘

In [132]:
 points = np.arange(-5, 5, 0.01) 

In [133]:
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [134]:
points.shape()

TypeError: 'tuple' object is not callable

In [135]:
points.shapes()

AttributeError: 'numpy.ndarray' object has no attribute 'shapes'

In [136]:
points.shape()

TypeError: 'tuple' object is not callable

In [137]:
len(points)

1000

In [138]:
np.shape(points)

(1000,)

In [139]:
xs , ys = np.meshgrid(points,points)

In [140]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [141]:
np.shape(ys)

(1000, 1000)

In [142]:
np.shape(xs)

(1000, 1000)

In [143]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [144]:
z = np.sqrt(xs**2+ ys**2)

In [145]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [147]:
# 数学和统计方法

In [148]:
# 可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算

In [149]:
arr = np.random.randn(5,4)

In [150]:
arr

array([[ 1.26272899,  0.40599619,  0.47100749, -0.89284075],
       [ 1.0101281 , -1.26778545,  0.35919538, -1.17177039],
       [-1.04394611,  1.15297836, -0.66333706, -1.38644489],
       [-0.17801294, -0.76015876,  0.06351274,  1.66342091],
       [-0.46648797,  0.65418003, -1.53044854,  0.25205809]])

In [151]:
arr.mean()

-0.10330132763169006

In [152]:
np.mean(arr)

-0.10330132763169006

In [153]:
arr.sum()

-2.0660265526338013

In [154]:
np.sum(arr)

-2.0660265526338013

In [155]:
# mean 和 sum 这类函数可以接收一个axis选项参数，用于计算该轴向上的统计值

In [156]:
arr.mean(axis = 1)

array([ 0.31172298, -0.26755809, -0.48518742,  0.19719049, -0.27267459])

In [157]:
arr.sum(axis=1)

array([ 1.24689192, -1.07023236, -1.94074969,  0.78876195, -1.09069838])

In [158]:
arr.sum(axis=0)

array([ 0.58441008,  0.18521038, -1.30006999, -1.53557703])

In [159]:
arr = np.random.randn(100)

In [160]:
(arr > 0).sum() 

58

In [161]:
# any 用于测试数组中是否有一个或者多个 True 而 all 则检查数组找那个所有值是否都是 True

In [162]:
# 排序

In [163]:
arr = np.random.randn(10)

In [164]:
arr

array([ 1.44893232, -0.49691125,  1.20094131,  0.1910961 ,  0.19180854,
       -0.0945741 , -1.07397635,  0.80785496,  0.87466665, -1.10345305])

In [165]:
arr.sort()

In [166]:
arr

array([-1.10345305, -1.07397635, -0.49691125, -0.0945741 ,  0.1910961 ,
        0.19180854,  0.80785496,  0.87466665,  1.20094131,  1.44893232])

In [167]:
arr = np.random.randn(3,6)

In [168]:
arr

array([[-2.0691695 , -0.10306676,  0.9662919 , -1.28128518,  0.63422294,
        -0.37895406],
       [ 0.20212861, -1.01811685,  0.83538927, -0.71811647,  1.26661027,
        -0.84277769],
       [-0.90225055,  2.28151978,  0.55788448, -1.69439359, -0.04650896,
        -0.14296751]])

In [169]:
arr = np.random.randn(3,5)

In [170]:
arr

array([[-1.20172724,  0.32276811,  0.36512021, -1.17296001,  1.36727857],
       [-0.70049969, -3.65676674,  1.48897577, -0.04444469,  0.63273534],
       [ 0.78515793,  1.04778357,  0.62395271, -1.04510164, -1.26178912]])

In [171]:
arr.sort(axis = 1)

In [172]:
arr

array([[-1.20172724, -1.17296001,  0.32276811,  0.36512021,  1.36727857],
       [-3.65676674, -0.70049969, -0.04444469,  0.63273534,  1.48897577],
       [-1.26178912, -1.04510164,  0.62395271,  0.78515793,  1.04778357]])

In [173]:
arr.sort(0)

In [174]:
arr

array([[-3.65676674, -1.17296001, -0.04444469,  0.36512021,  1.04778357],
       [-1.26178912, -1.04510164,  0.32276811,  0.63273534,  1.36727857],
       [-1.20172724, -0.70049969,  0.62395271,  0.78515793,  1.48897577]])

In [175]:
# 用于数组的文件输入和输出

In [176]:
# np.save 和 np.load 是读写磁盘数组数据的两个主要函数

In [177]:
# 默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为.npy的文件中

In [178]:
arr = np.aragne(10)

AttributeError: module 'numpy' has no attribute 'aragne'

In [179]:
arr = np.arange(10)

In [180]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
np.save('some_array',arr)

In [182]:
np.load('some_array')

FileNotFoundError: [Errno 2] No such file or directory: 'some_array'

In [183]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
# savez可以将多个数组保存到一个未压缩的文件中

In [185]:
np.savez('array1',arr,arr)

In [186]:
aaa = np.load('array1.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'array1.npy'

In [187]:
aaa = np.load('array1.npz')

In [188]:
aaa

In [189]:
list(aaa)

['arr_0', 'arr_1']

In [190]:
aaa[0]

KeyError: '0 is not a file in the archive'

In [191]:
aaa['a']

KeyError: 'a is not a file in the archive'

In [192]:
aaa['b']

KeyError: 'b is not a file in the archive'

In [193]:
list(aaa)

['arr_0', 'arr_1']

In [194]:
aaa['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
arr['arr_1']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [196]:
arr['arr_1']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [197]:
# dot函数

In [198]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [199]:
 y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [200]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [201]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [202]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [203]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [204]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [205]:
np.dot(y,x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [206]:
# 伪随机数生成

In [207]:
# np.random 模块对pyHton 内置的random进行了不是，增加了一些用于高效生成多种概率分布的样本值的函数

In [208]:
samples = np.random.normal(size=(4,4))

In [209]:
samples

array([[-0.63229425, -0.25216596, -0.98512396,  0.15658803],
       [-0.34924512,  0.37921254,  0.54579035,  0.79398042],
       [-1.23253007,  0.73553382, -0.37647095, -1.47087991],
       [-0.94840105, -0.21968835,  0.65632396, -0.2701001 ]])

In [210]:
# 之所以说是伪随机数，是因为它们都是通过算法基于随机生成器种子，在确定的条件下生成的
# 更改 np.random.seed 就可以更改随机数生成种子

In [211]:
np.random.seed(1234)

In [213]:
# np.random的数据生成函数使用了全局的随机种子，要避免全局状态可以使用numpy.random.RandomState，创建一个与其它隔离的随机数生成器

In [214]:
rng.randn()

NameError: name 'rng' is not defined

In [215]:
rng.randn(10)

NameError: name 'rng' is not defined

In [216]:
rng = np,random.RandomState(10)

NameError: name 'random' is not defined

In [217]:
rng = np.random.RandomState(10)

In [218]:
rng.randn(10)

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [219]:
np.random.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [220]:
rng.randn(10)

array([ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013,
        0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489])

In [221]:
rng.randn(10)

array([-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125,
        1.67262221,  0.09914922,  1.39799638, -0.27124799,  0.61320418])

In [222]:
np.random.randn(10)

array([ 1.15003572,  0.99194602,  0.95332413, -2.02125482, -0.33407737,
        0.00211836,  0.40545341,  0.28909194,  1.32115819, -1.54690555])

In [223]:
rng = np.random.RandomState(10)

In [224]:
rng.randn(10)

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [225]:
rng = np.random.RandomState(10)

In [226]:
rng.randn(10)

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [227]:
np.random.seed = 10

In [228]:
np.random.randn(10)

array([-0.20264632, -0.65596934,  0.19342138,  0.55343891,  1.31815155,
       -0.46930528,  0.67555409, -1.81702723, -0.18310854,  1.05896919])

In [229]:
np.random.randn(10)

array([-0.39784023,  0.33743765,  1.04757857,  1.04593826,  0.86371729,
       -0.12209157,  0.12471295, -0.32279481,  0.84167471,  2.39096052])

In [230]:
np.random.seed = 10

In [231]:
np.random.randn(10)

array([ 0.07619959, -0.56644593,  0.03614194, -2.0749776 ,  0.2477922 ,
       -0.89715678, -0.13679483,  0.01828919,  0.75541398,  0.21526858])

In [232]:
np.random.seed = 10

In [233]:
np.random.randn(10)

array([ 0.84100879, -1.44581008, -1.40197328, -0.1009182 , -0.54824245,
       -0.14461951,  0.35402033, -0.03551303,  0.56573831,  1.5456588 ])

In [234]:
np.random.seed(10)

TypeError: 'int' object is not callable

In [235]:
np.random.seed（1234）

SyntaxError: invalid character in identifier (<ipython-input-235-3a6f2bc2fa1a>, line 1)

In [236]:
np.random.seed(1234)

TypeError: 'int' object is not callable

In [237]:
np.random.seed(1234)


TypeError: 'int' object is not callable

In [238]:
np.random.seed(1234)

TypeError: 'int' object is not callable

In [239]:
np.random.seed(0.1)

TypeError: 'int' object is not callable

In [240]:
np.random.seed(5)

TypeError: 'int' object is not callable

In [241]:
np.random.seed

10

In [242]:
np.random.seed = 11

In [243]:
np.random.seed

11

In [244]:
np.random.seed(1)

TypeError: 'int' object is not callable

In [245]:
np.random.seed = 11

In [246]:
np.random.randn(10)

array([-0.97423633, -0.07034488,  0.30796886, -0.20849876,  1.03380073,
       -2.40045363,  2.03060362, -1.14263129,  0.21188339,  0.70472062])

In [247]:
np.random.seed = 11

In [248]:
np.random.randn(10)

array([-0.78543521,  0.46205974,  0.70422823,  0.52350797, -0.92625431,
        2.00784295,  0.22696254, -1.15265911,  0.63197945,  0.03951269])

In [249]:
import numpy as np

In [250]:
np.random.seed

11

In [251]:
np.random.seed(10)

TypeError: 'int' object is not callable

In [252]:
np.random.seed(3)

TypeError: 'int' object is not callable

In [ ]:
# seed 可以理解为种子，种子一样，产生的随机序列一样